# Form implementation generated from reading ui file 'successful_registration.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Успешная регистрация")
        Form.resize(371, 117)
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setBold(True)
        Form.setFont(font)
        self.OK_Button = QtWidgets.QPushButton(parent=Form)
        self.OK_Button.setGeometry(QtCore.QRect(240, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        self.OK_Button.setFont(font)
        self.OK_Button.setObjectName("OK_Button")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(40, 30, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.OK_Button.setText(_translate("Form", "ОК"))
        self.label.setText(_translate("Form", "Вы успешно зарегистрированы!"))
